ALTER TABLE album ADD COLUMN IF NOT EXISTS release_date VARCHAR(32);
ALTER TABLE album ADD COLUMN IF NOT EXISTS release_type VARCHAR(64);
ALTER TABLE album ADD COLUMN IF NOT EXISTS album_info_json TEXT;
