CREATE TABLE IF NOT EXISTS album_artist (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    album_id UUID NOT NULL REFERENCES album(id) ON DELETE CASCADE,
    artist_id UUID NOT NULL REFERENCES artist(id) ON DELETE CASCADE,
    position INTEGER NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS index_album_artist_album_id_artist_id ON album_artist(album_id, artist_id);
CREATE INDEX IF NOT EXISTS index_album_artist_album_id_fk ON album_artist(album_id);
CREATE INDEX IF NOT EXISTS index_album_artist_artist_id_fk ON album_artist(artist_id);

CREATE TABLE IF NOT EXISTS track_artist (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    track_id UUID NOT NULL REFERENCES track(id) ON DELETE CASCADE,
    artist_id UUID NOT NULL REFERENCES artist(id) ON DELETE CASCADE,
    position INTEGER NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS index_track_artist_track_id_artist_id ON track_artist(track_id, artist_id);
CREATE INDEX IF NOT EXISTS index_track_artist_track_id_fk ON track_artist(track_id);
CREATE INDEX IF NOT EXISTS index_track_artist_artist_id_fk ON track_artist(artist_id);

CREATE TABLE IF NOT EXISTS image (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    path VARCHAR(4096) NOT NULL,
    image_type VARCHAR(10) NOT NULL,
    related_id UUID NOT NULL,
    created TIMESTAMP NOT NULL
);
